In [3]:
import pandas as pd
# 문제 1
df = pd.DataFrame({
    '이름': ['철수', '영희', '민수'],
    '나이': [20, 21, 22],
    '학과': ['컴퓨터', 'AI', '디자인']
})

print(df)

   이름  나이   학과
0  철수  20  컴퓨터
1  영희  21   AI
2  민수  22  디자인

In [5]:
import seaborn as sns
# 문제 2
df = sns.load_dataset('titanic')
df.loc[:, ['age', 'fare']]

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [6]:
# 문제 3
df.iloc[[0, -1],:]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [10]:
# 문제 4
df = pd.DataFrame({
    '학생': ['철수', '영희', '민수'],
    '국어': [90, 85, 70],
    '영어': [80, 95, 75],
    '수학': [70, 88, 92]
})

df.drop(['영어'], axis=1)

   학생  국어  수학
0  철수  90  70
1  영희  85  88
2  민수  70  92

In [9]:
# 문제 5
import seaborn as sns
df = sns.load_dataset('titanic')
df2 = df.loc[:, ['age', 'fare', 'survived']]
df2.head(10)

    age     fare  survived
0  22.0   7.2500         0
1  38.0  71.2833         1
2  26.0   7.9250         1
3  35.0  53.1000         1
4  35.0   8.0500         0
5   NaN   8.4583         0
6  54.0  51.8625         0
7   2.0  21.0750         0
8  27.0  11.1333         1
9  14.0  30.0708         1