In [2]:
import pandas as pd
df = pd.read_csv('./data/read_csv_sample.csv')
print(df)
print(df.info())

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c0      3 non-null      int64
 1   c1      3 non-null      int64
 2   c2      3 non-null      int64
 3   c3      3 non-null      int64
dtypes: int64(4)
memory usage: 228.0 bytes
None

In [ ]:
import pandas as pd

# 경로 폴더의 모든 파일 목록 확인하기
import os
os.listdir('./data')
os.listdir('../') # 상위폴더

['df_excelwriter.xlsx',
 'df_sample.csv',
 'df_sample.json',
 'df_sample.xlsx',
 'df_sample_columns.json',
 'df_sample_index.json',
 'df_sample_no_index.csv',
 'df_sample_no_index.xlsx',
 'df_sample_records.json',
 'df_sample_split.json',
 'df_sample_values.json',
 'read_csv_sample.csv',
 'read_json_sample.json',
 'sample.html',
 'test.csv',
 'test.json',
 '남북한발전전력량.xlsx']

In [4]:
file_path = "./data/read_csv_sample.csv"
print(file_path)

./data/read_csv_sample.csv

In [5]:
# 파일경로를 찾고, 변수 file_path에 저장(문자열 결합)
file_path2 = os.path.join('data', 'read_csv_sample.csv')
print(file_path2)

data\read_csv_sample.csv

In [6]:
# read_csv() 함수로 데이터프레임 변환. 변수 df1에 저장
df1 = pd.read_csv(file_path)
print(df1)

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [22]:
file_path2 = 'C:/Users/KDT59/Desktop/wonik/mini_project1/yahooFinanceData2017to2026.xlsx'
df2 = pd.read_excel(file_path2)
print(df2)

           Date  WonikQnC      KOSDAQ        KOSPI  SamsungElec  SKHynix  \
0    2017-07-06     11900  663.789978  2387.810059        48060    68100
1    2017-07-07     11850  663.770020  2379.870117        47860    66600
2    2017-07-10     11900  657.859985  2382.100098        48660    67300
3    2017-07-11     12350  656.010010  2396.000000        49000    69000
4    2017-07-12     12100  651.099976  2391.770020        49880    68900
...         ...       ...         ...          ...          ...      ...
2326 2026-06-30     35150  916.179993  8476.480469       334000  2650000
2327 2026-07-01     36850  929.349976  8303.410156       314500  2560000
2328 2026-07-02     31700  866.719971  7648.089844       286000  2187000
2329 2026-07-03     31200  868.409973  8088.339844       309500  2425000
2330 2026-07-06     31150  847.070007  8051.330078       318000  2343000

      WonikIPS        SOXX         SMH
0        29250   46.830002   41.055000
1        30400   47.619999   41.605000
2        29950   48.169998   42.035000
3        30200   48.570000   42.369999
4        29750   49.346668   42.980000
...        ...         ...         ...
2326    168100  640.760010  655.890015
2327    165600  599.700012  620.460022
2328    131600  566.320007  592.289978
2329    133100  566.320007  592.289978
2330    124500  581.510010  604.299988

[2331 rows x 9 columns]

In [10]:
# read_csv() 함수로 데이터프레임 변환. 변수 df2에 저장. header=None 옵션
df2 = pd.read_csv(file_path, header=None)
print(df2)

# read_csv() 함수로 데이터프레임 변환. 변수 df3에 저장. index_col=None 옵션
df3 = pd.read_csv(file_path, index_col=False)
print(df3)

# read_csv() 함수로 데이터프레임 변환. 변수 df4에 저장. index_col='c0' 옵션
df4 = pd.read_csv(file_path, index_col='c0')
print(df4)

    0   1   2   3
0  c0  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9
   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9
    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9

In [13]:
import pandas as pd
import openpyxl

# read_excel() 함수로 데이터프레임 변환: header=0(default option)
# openpyxl 설치 필요
df1 = pd.read_excel('./data/남북한발전전력량.xlsx', engine='openpyxl')

# 데이터프레임 출력
df1.head()

,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,남한,합계,1077,1186,1310,1444,1650,1847,2055,2244,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
1,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
2,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
3,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
4,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195

In [14]:
# read_excel() 함수로 데이터프레임 변환: header=None 옵션
df2 = pd.read_excel('./data/남북한발전전력량.xlsx', engine='openpyxl', header=None)

# 데이터프레임 출력
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
1,남한,합계,1077,1186,1310,1444,1650,1847,2055,2244,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
2,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
3,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
4,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620

In [16]:
import pandas as pd

# read_json() 함수로 데이터프레임 변환
df = pd.read_json('./data/read_json_sample.json')
print(df)

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True

In [17]:
df.index

Index(['pandas', 'NumPy', 'matplotlib'], dtype='str')

In [18]:
# orient 속성: 'index'
df2 = pd.read_json('./data/read_json_sample.json', orient='index')
df2

                   pandas            NumPy      matplotlib
year                 2008             2006            2003
developer   Wes Mckinneye  Travis Oliphant  John D. Hunter
opensource           True             True            True

In [19]:
df3 = pd.read_json('./data/read_json_sample.json', orient='columns')
df3

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True