# json 파일 불러오기
- 자바스크립트에서 유래한 데이터 공유를 목적으로 개발된 특수 파일 형식
  파이썬 딕셔너리 형태와 유사하게 'key: value' 구조를 가짐
  read_json() 함수를 사용해서 JSON파일일 데이터프레임으로 변환

In [2]:
import pandas as pd
df = pd.read_json('../data/read_json_sample.json')
df

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True

In [3]:
# 인덱스 출력
df.index

Index(['pandas', 'NumPy', 'matplotlib'], dtype='str')

In [6]:
df2 = pd.read_json('../data/read_json_sample.json', orient='index')
df2

                   pandas            NumPy      matplotlib
year                 2008             2006            2003
developer   Wes Mckinneye  Travis Oliphant  John D. Hunter
opensource           True             True            True

In [10]:
df3 = pd.read_json('../data/read_json_sample.json', orient='column')
df3

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True

In [ ]:
# transpose()는 행과 열의 위치를 서로 바꾸는 메서드
print(df3.T)

                   pandas            NumPy      matplotlib
year                 2008             2006            2003
developer   Wes Mckinneye  Travis Oliphant  John D. Hunter
opensource           True             True            True

# html 파일 불러오기
- read_html() 함수는 HTML 웹페이지에 있는 태그를 표형식의 데이터로 모두 찾아서 데이터프레임으로 반환
- 표가 아닌 다른 HTML 요소는 DataFrame으로 반환하지 못함

In [13]:
import pandas as pd

tables = pd.read_html('../data/sample.html')
print(tables)

[   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9,          name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True]

In [14]:
print(len(tables))

2

In [15]:
tables[0]

   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9

In [ ]:
# tables 리스트의 원소를 반복하면서 각각 출력
for i in range(len(tables)):
    print(tables[i])
    print()

   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [20]:
df = tables[1]
df

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [23]:
df = df.set_index('name')
df

            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True

In [24]:
tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_American_exchange-traded_funds')
print(tables)

HTTPError: HTTP Error 403: Forbidden

In [ ]:
import requests
from bs4 import BeautifulSoup
from io import StringIO # 메모리에있는 문자열을 파일처럼 쓸수있게해주는것

url = 'https://en.wikipedia.org/wiki/Korea'

headers={
    'User-Agent': 'Mozilla/5.0' # 나는 브라우저야 라고 뻥카날리기
}

response = requests.get(url, headers=headers)
tables = pd.read_html(StringIO(response.text))

print(len(tables))
print(type(tables))
print(tables[0])
for table in tables:
    print(table)
    print()

28
<class 'list'>
                                0  \
0       Korea shown in dark green
1                       Geography
2                   Major islands
3                            Area
4                  Administration
5                     North Korea
6                    Capital city
7   Supreme Leader of North Korea
8                     South Korea
9                    Capital city
10       President of South Korea
11                   Demographics
12                        Demonym
13                     Population
14                   Pop. density
15                      Languages
16         Additional information
17                      Time zone
18                            NaN
19                            NaN
20              South Korean name
21                         Hangul
22                          Hanja
23                             RR
24                             MR
25              North Korean name
26                         Hangul
27                          Hanja
28                             RR
29                             MR

                                                  1
0                         Korea shown in dark green
1                                         Geography
2                                       Jeju Island
3                        223,915 km2 (86,454 sq mi)
4                                    Administration
5                                       North Korea
6                                         Pyongyang
7                                    Kim Jong Un[a]
8                                       South Korea
9                                             Seoul
10                                    Lee Jae Myung
11                                     Demographics
12                                           Korean
13                                77,620,000 (2025)
14                        346.65/km2 (897.82/sq mi)
15                                           Korean
16                           Additional information
17  Korea Standard Time and Pyongyang Time (UTC+09)
18                                              NaN
19                                              NaN
20                                South Korean name
21                                               한국
22                                               韓國
23                                           Hanguk
24                                          Han'guk
25                                North Korean name
26                                               조선
27                                               朝鮮
28                                           Joseon
29                                           Chosŏn
                                0  \
0       Korea shown in dark green
1                       Geography
2                   Major islands
3                            Area
4                  Administration
5                     North Korea
6                    Capital city
7   Supreme Leader of North Korea
8                     South Korea
9                    Capital city
10       President of South Korea
11                   Demographics
12                        Demonym
13                     Population
14                   Pop. density
15                      Languages
16         Additional information
17                      Time zone
18                            NaN
19                            NaN
20              South Korean name
21                         Hangul
22                          Hanja
23                             RR
24                             MR
25              North Korean name
26                         Hangul
27                          Hanja
28                             RR
29                             MR

                                                  1
0                         Korea shown in dark green
1                                         Geography
2                                       Jeju Island
3                        223,915 km2 (86,454 sq mi)
4                                    Administration
5                                       North Korea
6                                         Pyongyang
7                                    Kim Jong Un[a]
8                                       South Korea
9                                             Seoul
10                                    Lee Jae Myung
11                                     Demographics
12                                           Korean
13                                77,620,000 (2025)
14                        346.65/km2 (897.82/sq mi)
15                                           Korean
16                           Additional information
17  Korea Standard Time and Pyongyang Time (UTC+09)
18                                              NaN
19                                              NaN
20                                South Korean name
21                                               한국
22                                               韓國
23                                           Hanguk
24                                          Han'guk
25                                North Korean name
26                                               조선
27                                               朝鮮
28                                           Joseon
29                                           Chosŏn

                              Part of a series on the  Unnamed: 1_level_0
                                     History of Korea  Unnamed: 1_level_1
0                                                 NaN                 NaN
1   Prehistoric period Palaeolithic 700,000–8000 B...                 NaN
2                                        Palaeolithic     700,000–8000 BC
3                                           Neolithic        8000–1500 BC
4                                           * Jeulmun                 NaN
5                                          Bronze Age         1500–300 BC
6                                             * Mumun                 NaN
7                                   * Liaoning dagger                 NaN
8   Ancient period Gojoseon 2333–108 BC* Tan'gun* ...                 NaN
9                                            Gojoseon         2333–108 BC
10                                          * Tan'gun                 NaN
11                                             * Kija                 NaN
12                                            * Wiman                 NaN
13                                                Jin  4th–2nd century BC
14                                             Yemaek                 NaN
15  Proto–Three Kingdoms period Takri Dongye Buyeo...                 NaN
16  Three Kingdoms period Goguryeo 37 BC – 668 AD ...                 NaN
17                                           Goguryeo      37 BC – 668 AD
18                                            Paekche      18 BC – 660 AD
19                                              Silla      57 BC – 935 AD
20                                   Kaya confederacy              42–562
21                       Tamna (Tributary of Paekche)             498–660
22                                               Usan             512–930
23  Northern and Southern period United Silla (Uni...                 NaN
24                       United Silla (Unified Silla)             668–892
25                                             Parhae             698–926
26                                    Little Goguryeo             699–820
27                         Tamna (Tributary of Silla)             662–925
28  Later Three Kingdoms period Later Paekche 892–...                 NaN
29                                      Later Paekche             892–936
30                           Taebong (Later Goguryeo)             901–918
31                        Unified Silla (Later Silla)             892–935
32                                       Later Sabeol             919–927
33                                    Dongdan Kingdom             926–936
34                                       Later Parhae             927–935
35                                            Jeongan             938–986
36  Dynastic period Goryeo 918–1392 Tamna (Vassal ...                 NaN
37                                             Goryeo            918–1392
38                           Tamna (Vassal of Goryeo)            938–1105
39                                            Heungyo           1029–1030
40                                        Mongol rule           1270–1356
41                                             Joseon           1392–1897
42                                      Korean Empire           1897–1910
43  Colonial period Japanese occupation 1910–1945 ...                 NaN
44                                Japanese occupation           1910–1945
45                             Provisional Government           1919–1948
46  Modern period Military governments 1945–1948 N...                 NaN
47                               Military governments           1945–1948
48                               North-South division        1945–present
49                                            * North        1948–present
50                                            * South        1948–present
51  By topic Architecture Art Cuisine Currency Edu...                 NaN
52                                           Timeline                 NaN
53              North Korea portal South Korea portal                 NaN
54                                                vte                 NaN

                   0                1
0       Palaeolithic  700,000–8000 BC
1          Neolithic     8000–1500 BC
2          * Jeulmun              NaN
3         Bronze Age      1500–300 BC
4            * Mumun              NaN
5  * Liaoning dagger              NaN

           0                   1
0   Gojoseon         2333–108 BC
1  * Tan'gun                 NaN
2     * Kija                 NaN
3    * Wiman                 NaN
4        Jin  4th–2nd century BC
5     Yemaek                 NaN

                              0               1
0                      Goguryeo  37 BC – 668 AD
1                       Paekche  18 BC – 660 AD
2                         Silla  57 BC – 935 AD
3              Kaya confederacy          42–562
4  Tamna (Tributary of Paekche)         498–660
5                          Usan         512–930

                              0        1
0  United Silla (Unified Silla)  668–892
1                        Parhae  698–926
2               Little Goguryeo  699–820
3    Tamna (Tributary of Silla)  662–925

                             0        1
0                Later Paekche  892–936
1     Taebong (Later Goguryeo)  901–918
2  Unified Silla (Later Silla)  892–935
3                 Later Sabeol  919–927
4              Dongdan Kingdom  926–936
5                 Later Parhae  927–935
6                      Jeongan  938–986

                          0          1
0                    Goryeo   918–1392
1  Tamna (Vassal of Goryeo)   938–1105
2                   Heungyo  1029–1030
3               Mongol rule  1270–1356
4                    Joseon  1392–1897
5             Korean Empire  1897–1910

                        0          1
0     Japanese occupation  1910–1945
1  Provisional Government  1919–1948

                      0             1
0  Military governments     1945–1948
1  North-South division  1945–present
2               * North  1948–present
3               * South  1948–present

    0                                                  1
0 NaN  This section does not cite any sources. Please...

    0                                                  1
0 NaN  This section may contain excessive or inapprop...

  Largest cities or towns in Korea Sources: 2008 North Korean census and 2015 South Korean census  \
                                                                                             Rank
0                                                  1
1                                                  2
2                                                  3
3                                                  4
4                                                  5
5                                                  6
6                                                  7
7                                                  8
8                                                  9
9                                                 10

                                                                             \
        Name          Province     Pop. Rank.1    Name.1         Province.1
0      Seoul             Seoul  9904312     11    Goyang           Gyeonggi
1      Busan             Busan  3448737     12    Yongin           Gyeonggi
2  Pyongyang         Pyongyang  3255288     13  Seongnam           Gyeonggi
3    Incheon           Incheon  2890451     14   Bucheon           Gyeonggi
4      Daegu             Daegu  2446052     15  Cheongju  North Chungcheong
5    Daejeon           Daejeon  1538394     16   Hamhung     South Hamgyong
6    Gwangju           Gwangju  1502881     17     Ansan           Gyeonggi
7      Suwon          Gyeonggi  1194313     18  Chongjin     North Hamgyong
8      Ulsan             Ulsan  1166615     19    Jeonju       North Jeolla
9   Changwon  South Gyeongsang  1059241     20   Cheonan  South Chungcheong


   Pop..1 Unnamed: 8_level_1 Unnamed: 9_level_1
0  990073                NaN                NaN
1  971327                NaN                NaN
2  948757                NaN                NaN
3  843794                NaN                NaN
4  833276                NaN                NaN
5  768551                NaN                NaN
6  747035                NaN                NaN
7  667929                NaN                NaN
8  658172                NaN                NaN
9  629062                NaN                NaN

    0                                                  1
0 NaN  This section does not cite any sources. Please...

                   vteIndex of Korea-related articles  \
0                             North Korea South Korea
1   History of KoreaGeneral Military history Monar...
2                                    History of Korea
3   General Military history Monarchs Timeline Chr...
4                                             General
5                                          Chronology
6   Geography of KoreaGeneral Borders Korean Penin...
7                                  Geography of Korea
8   General Borders Korean Peninsula Islands Lakes...
9                                             General
10                           Geography of North Korea
11                           Geography of South Korea
12  PoliticsNorth Korea Overview Constitution Fore...
13                                           Politics
14  North Korea Overview Constitution Foreign rela...
15                                        North Korea
16                                        South Korea
17  EconomyNorth Korea Overview Agriculture Automo...
18                                            Economy
19  North Korea Overview Agriculture Automotive in...
20                                        North Korea
21                                        South Korea
22  Demographics Koreans Demographics of North Kor...
23                                       Demographics
24  Koreans Demographics of North Korea Demographi...
25  Culture of KoreaGeneral Cinema North South 100...
26                                   Culture of Korea
27  General Cinema North South 100 Cultural Symbol...
28                                            General
29                                         Korean art
30                             Culture of North Korea
31                             Culture of South Korea

                 vteIndex of Korea-related articles.1
0                             North Korea South Korea
1   History of KoreaGeneral Military history Monar...
2                                    History of Korea
3   General Military history Monarchs Timeline Chr...
4                  Military history Monarchs Timeline
5   Gojoseon Dangun Joseon / Gija Joseon / Wiman J...
6   Geography of KoreaGeneral Borders Korean Penin...
7                                  Geography of Korea
8   General Borders Korean Peninsula Islands Lakes...
9   Borders Korean Peninsula Islands Lakes Mountai...
10  Administrative divisions Cities Special cities...
11  Administrative divisions Environment Cities Sp...
12  PoliticsNorth Korea Overview Constitution Fore...
13                                           Politics
14  North Korea Overview Constitution Foreign rela...
15  Overview Constitution Foreign relations Relati...
16  Overview Constitution Foreign relations Relati...
17  EconomyNorth Korea Overview Agriculture Automo...
18                                            Economy
19  North Korea Overview Agriculture Automotive in...
20  Overview Agriculture Automotive industry Energ...
21  Overview Agriculture Automotive industry Chaeb...
22  Demographics Koreans Demographics of North Kor...
23                                       Demographics
24  Koreans Demographics of North Korea Demographi...
25  Culture of KoreaGeneral Cinema North South 100...
26                                   Culture of Korea
27  General Cinema North South 100 Cultural Symbol...
28  Cinema North South 100 Cultural Symbols Cuisin...
29  Architecture Calligraphy Drama Literature Trad...
30  Education Literature Religion Smoking Sport Ar...
31  Education Literature Religion Smoking Sport Cu...

                                    History of Korea  \
0  General Military history Monarchs Timeline Chr...
1                                            General
2                                         Chronology

                                  History of Korea.1
0  General Military history Monarchs Timeline Chr...
1                 Military history Monarchs Timeline
2  Gojoseon Dangun Joseon / Gija Joseon / Wiman J...

            0                                                  1
0     General                 Military history Monarchs Timeline
1  Chronology  Gojoseon Dangun Joseon / Gija Joseon / Wiman J...

                                  Geography of Korea  \
0  General Borders Korean Peninsula Islands Lakes...
1                                            General
2                           Geography of North Korea
3                           Geography of South Korea

                                Geography of Korea.1
0  General Borders Korean Peninsula Islands Lakes...
1  Borders Korean Peninsula Islands Lakes Mountai...
2  Administrative divisions Cities Special cities...
3  Administrative divisions Environment Cities Sp...

                          0                                                  1
0                   General  Borders Korean Peninsula Islands Lakes Mountai...
1  Geography of North Korea  Administrative divisions Cities Special cities...
2  Geography of South Korea  Administrative divisions Environment Cities Sp...

                                            Politics  \
0  North Korea Overview Constitution Foreign rela...
1                                        North Korea
2                                        South Korea

                                          Politics.1
0  North Korea Overview Constitution Foreign rela...
1  Overview Constitution Foreign relations Relati...
2  Overview Constitution Foreign relations Relati...

             0                                                  1
0  North Korea  Overview Constitution Foreign relations Relati...
1  South Korea  Overview Constitution Foreign relations Relati...

                                             Economy  \
0  North Korea Overview Agriculture Automotive in...
1                                        North Korea
2                                        South Korea

                                           Economy.1

In [32]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO

In [40]:
# 스크래핑할 웹페이지 주소
url = 'https://ko.wikipedia.org/wiki/파이썬'
headers={
    'User-Agent': 'Mozilla/5.0' # 나는 브라우저야 라고 뻥카날리기
}

response = requests.get(url=url, headers=headers)
print(response.status_code)

soup = BeautifulSoup(response.text, 'html.parser')
soup.select('title')

200

In [43]:
#mwASM
#mw-content-text > div.mw-content-ltr.mw-parser-output
print(soup.a)

<a class="mw-jump-link" href="#bodyContent">본문으로 이동</a>

# p 태그 문단 가져오기
- html에서 p태그는 문단을 의미
- find_all()은 조건에 맞는 태그를 모두 찾아 리스트처럼 변환

In [48]:
paragraphs = soup.find_all('p')
print(paragraphs[0].text)
print(len(paragraphs))


for i in range(3):
    print(paragraphs[i])

파이썬[2](영어: Python)은 1991년[3] 네덜란드계 소프트웨어 엔지니어인 귀도 반 로섬[4]이 발표한 고급 프로그래밍 언어로, '인터프리터를 사용하는 객체지향 언어'이자 플랫폼에 독립적인, 동적 타이핑(dynamically typed) 대화형 언어다. 파이썬이라는 이름은 귀도가 좋아하는 코미디인〈Monty Python's Flying Circus〉에서 따온 것이다. 이름에서 고대신화에 나오는 커다란 뱀을 연상하겠지만 이와는 무관하다. 다만 로고에는 뱀 두마리가 형상화되어 있다. 간결하고 읽기 쉬운 문법이 특징인 프로그래밍 언어로 데이터 분석, 웹 개발, 인공지능 등 다양한 분야에서 활용된다.
45
<p id="mwCw"><b id="mwDA">파이썬</b><sup about="#mwt10" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-2"}}' id="cite_ref-2" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-2" id="mwDQ"><span class="mw-reflink-text" id="mwDg"><span class="cite-bracket" id="mwDw">[</span>2<span class="cite-bracket" id="mwEA">]</span></span></a></sup>(<span about="#mwt7" data-mw='{"parts":[{"template":{"target":{"wt":"llang","href":"./틀:Llang"},"params":{"1":{"wt":"en"},"2":{"wt":"Python"}},"i":0}}]}' id="mwEQ" style="font-size: smaller;" typeof="mw:Transclusion"><a href="//ko.wikipedia.org/wiki/영어" rel="mw:WikiLink" title="영어">영어</a><span typeof="mw:Entity">:</span> </span><span about="#mwt7" lang="en">Python</span><link about="#mwt7" href="./분류:영어_표기를_포함한_문서#파이썬" id="mwEg" rel="mw:PageProp/Category"/>)은 1991년<sup about="#mwt12" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"파이썬 역사"},"body":{"id":"mw-reference-text-cite_note-파이썬_역사-3"}}' id="cite_ref-파이썬_역사_3-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-파이썬_역사-3" id="mwEw"><span class="mw-reflink-text" id="mwFA"><span class="cite-bracket" id="mwFQ">[</span>3<span class="cite-bracket" id="mwFg">]</span></span></a></sup> 네덜란드계 <a class="mw-redirect" href="//ko.wikipedia.org/wiki/소프트웨어_엔지니어" id="mwFw" rel="mw:WikiLink" title="소프트웨어 엔지니어">소프트웨어 엔지니어</a>인 <a href="//ko.wikipedia.org/wiki/귀도_반_로섬" id="mwGA" rel="mw:WikiLink" title="귀도 반 로섬">귀도 반 로섬</a><sup about="#mwt13" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-4"}}' id="cite_ref-4" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-4" id="mwGQ"><span class="mw-reflink-text" id="mwGg"><span class="cite-bracket" id="mwGw">[</span>4<span class="cite-bracket" id="mwHA">]</span></span></a></sup>이 발표한 고급 <a href="//ko.wikipedia.org/wiki/프로그래밍_언어" id="mwHQ" rel="mw:WikiLink" title="프로그래밍 언어">프로그래밍 언어</a>로, '<a href="//ko.wikipedia.org/wiki/인터프리터" id="mwHg" rel="mw:WikiLink" title="인터프리터">인터프리터</a>를 사용하는 <a class="mw-redirect" href="//ko.wikipedia.org/wiki/객체지향" id="mwHw" rel="mw:WikiLink" title="객체지향">객체지향</a> 언어'이자 <a class="mw-disambig" href="//ko.wikipedia.org/wiki/플랫폼" id="mwIA" rel="mw:WikiLink" title="플랫폼">플랫폼</a>에 독립적인, <a class="mw-redirect" href="//ko.wikipedia.org/wiki/동적_타이핑" id="mwIQ" rel="mw:WikiLink" title="동적 타이핑">동적 타이핑</a>(dynamically typed) 대화형 언어다. 파이썬이라는 이름은 귀도가 좋아하는 코미디인〈Monty Python's Flying Circus〉에서 따온 것이다. 이름에서 <a href="//ko.wikipedia.org/wiki/피톤" id="mwIg" rel="mw:WikiLink" title="피톤">고대신화에 나오는 커다란 뱀</a>을 연상하겠지만 이와는 무관하다. 다만 로고에는 뱀 두마리가 형상화되어 있다. 간결하고 읽기 쉬운 문법이 특징인 <a href="//ko.wikipedia.org/wiki/프로그래밍_언어" id="mwIw" rel="mw:WikiLink" title="프로그래밍 언어">프로그래밍 언어</a>로 <a href="//ko.wikipedia.org/wiki/데이터_분석" id="mwJA" rel="mw:WikiLink" title="데이터 분석">데이터 분석</a>, <a href="//ko.wikipedia.org/wiki/웹_개발" id="mwJQ" rel="mw:WikiLink" title="웹 개발">웹 개발</a>, <a href="//ko.wikipedia.org/wiki/인공지능" id="mwJg" rel="mw:WikiLink" title="인공지능">인공지능</a> 등 다양한 분야에서 활용된다.</p>
<p id="mwJw">파이썬은 비영리 <a href="//ko.wikipedia.org/wiki/파이썬_소프트웨어_재단" id="mwKA" rel="mw:WikiLink" title="파이썬 소프트웨어 재단">파이썬 소프트웨어 재단</a>이 관리하는 개방형, 공동체 기반 개발 모델이 있다.</p>
<p id="mwKQ">가독성이 높고 표현력이 풍부한 문법이 특징인 <a href="//ko.wikipedia.org/wiki/프로그래밍_언어" id="mwKg" rel="mw:WikiLink" title="프로그래밍 언어">프로그래밍 언어</a>로, 적은 양의 코드로 효율적인 구현이 가능하여 <a href="//ko.wikipedia.org/wiki/데이터_분석" id="mwKw" rel="mw:WikiLink" title="데이터 분석">데이터 분석</a>, <a href="//ko.wikipedia.org/wiki/웹_개발" id="mwLA" rel="mw:WikiLink" title="웹 개발">웹 개발</a>, <a href="//ko.wikipedia.org/wiki/인공지능" id="mwLQ" rel="mw:WikiLink" title="인공지능">인공지능</a> 등 다양한 분야에서 활용된다.<sup about="#mwt15" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-5" id="mwLg"><span class="mw-reflink-text" id="mwLw"><span class="cite-bracket" id="mwMA">[</span>5<span class="cite-bracket" id="mwMQ">]</span></span></a></sup>
파이썬 인터프리터와 방대한 표준 라이브러리는 주요 플랫폼에서 소스 또는 바이너리 형태로 자유롭게 제공된다.<sup about="#mwt17" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-6"}}' id="cite_ref-6" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-6" id="mwMg"><span class="mw-reflink-text" id="mwMw"><span class="cite-bracket" id="mwNA">[</span>6<span class="cite-bracket" id="mwNQ">]</span></span></a></sup></p>

In [ ]:
paragraphs_list = []

# 모든 p 태그를 순회하면서 하나씩 반복하는데 
# 문자열의 앞뒤 공백을 없애고 줄바꿈 등을 제거
for p in paragraphs:
    text = p.text.strip()

    # 빈 문단을 제거하고 리스트에 넣어
    if text != "":
        paragraphs_list.append(text)


# 리스트를 데이터 프레임으로 변환
paragraph_df = pd.DataFrame(paragraphs_list, columns=['문단'])

# 상위 5개 행 확인
print(paragraph_df.head())

                                                  문단
0  파이썬[2](영어: Python)은 1991년[3] 네덜란드계 소프트웨어 엔지니어인...
1  파이썬은 비영리 파이썬 소프트웨어 재단이 관리하는 개방형, 공동체 기반 개발 모델이...
2  가독성이 높고 표현력이 풍부한 문법이 특징인 프로그래밍 언어로, 적은 양의 코드로 ...
3  2026년 3월 발표된 TIOBE 프로그래밍 언어 인기 지수에서 파이썬은 21.25...
4  파이썬은 다중 패러다임 프로그래밍 언어로, 객체 지향 프로그래밍과 구조적 프로그래밍...

# a태그에서 텍스트랑 링크 정보 가져오기
- HTML 에서 a태그는 링크를 의미
- link.text: 링크가 걸린 글자를 의미
- link.get('속성명 ex) href'): 링크 주소

In [56]:
links = soup.find_all('a')

for link in links:
    print('글자', link.text.strip())
    print(link.get('href'))

글자 본문으로 이동
#bodyContent
글자 대문
/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EB%8C%80%EB%AC%B8
글자 최근 바뀜
/wiki/%ED%8A%B9%EC%88%98:%EC%B5%9C%EA%B7%BC%EB%B0%94%EB%80%9C
글자 요즘 화제
/wiki/%ED%8F%AC%ED%84%B8:%EC%9A%94%EC%A6%98_%ED%99%94%EC%A0%9C
글자 임의 문서로
/wiki/%ED%8A%B9%EC%88%98:%EC%9E%84%EC%9D%98%EB%AC%B8%EC%84%9C
글자 사랑방
/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EC%82%AC%EB%9E%91%EB%B0%A9
글자 사용자 모임
/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EC%82%AC%EC%9A%A9%EC%9E%90_%EB%AA%A8%EC%9E%84
글자 관리 요청
/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EC%9A%94%EC%B2%AD
글자 소개
/wiki/%EB%8F%84%EC%9B%80%EB%A7%90:%EC%86%8C%EA%B0%9C
글자 도움말
/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EB%8F%84%EC%9B%80%EB%A7%90
글자 정책과 지침
/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EC%A0%95%EC%B1%85%EA%B3%BC_%EC%A7%80%EC%B9%A8
글자 질문방
/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EC%A7%88%EB%AC%B8%EB%B0%A9
글자
/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EB%8C%80%EB%AC%B8
글자 검색
/wiki/%ED%8A%B9%EC%88%98:%EA%B2%80%EC%83%89
글자 기부
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=ko.wikipedia.org&uselang=ko
글자 계정 만들기
/w/index.php?title=%ED%8A%B9%EC%88%98:%EA%B3%84%EC%A0%95%EB%A7%8C%EB%93%A4%EA%B8%B0&returnto=%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 로그인
/w/index.php?title=%ED%8A%B9%EC%88%98:%EB%A1%9C%EA%B7%B8%EC%9D%B8&returnto=%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 기부
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=ko.wikipedia.org&uselang=ko
글자 계정 만들기
/w/index.php?title=%ED%8A%B9%EC%88%98:%EA%B3%84%EC%A0%95%EB%A7%8C%EB%93%A4%EA%B8%B0&returnto=%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 로그인
/w/index.php?title=%ED%8A%B9%EC%88%98:%EB%A1%9C%EA%B7%B8%EC%9D%B8&returnto=%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 처음 위치
#
글자 1
개요
#개요
글자 2
역사
#역사
글자 2.1
파이썬 2
#파이썬_2
글자 2.2
파이썬 3
#파이썬_3
글자 2.3
인기
#인기
글자 3
기능과 철학
#기능과_철학
글자 3.1
라이브러리
#라이브러리
글자 4
문법
#문법
글자 5
자료형
#자료형
글자 6
동작하는 플랫폼
#동작하는_플랫폼
글자 7
한글 다루기
#한글_다루기
글자 8
사용 현황
#사용_현황
글자 8.1
파이썬으로 작성된 자유-오픈 소스 소프트웨어
#파이썬으로_작성된_자유-오픈_소스_소프트웨어
글자 8.2
파이썬을 내부적으로 사용하는 소프트웨어
#파이썬을_내부적으로_사용하는_소프트웨어
글자 8.3
파이썬을 이용하고 있는 기업·정부 기관
#파이썬을_이용하고_있는_기업·정부_기관
글자 9
실행 속도 향상 관련
#실행_속도_향상_관련
글자 10
IDE 목록
#IDE_목록
글자 11
비평
#비평
글자 12
빌드
#빌드
글자 13
같이 보기
#같이_보기
글자 14
각주
#각주
글자 15
외부 링크
#외부_링크
글자 Afrikaans
https://af.wikipedia.org/wiki/Python_(programmeertaal)
글자 Alemannisch
https://als.wikipedia.org/wiki/Python_(Programmiersprache)
글자 Aragonés
https://an.wikipedia.org/wiki/Python
글자 العربية
https://ar.wikipedia.org/wiki/%D8%A8%D8%A7%D9%8A%D8%AB%D9%88%D9%86_(%D9%84%D8%BA%D8%A9_%D8%A8%D8%B1%D9%85%D8%AC%D8%A9)
글자 অসমীয়া
https://as.wikipedia.org/wiki/%E0%A6%AA%E0%A6%BE%E0%A6%87%E0%A6%A5%E0%A6%A8
글자 Asturianu
https://ast.wikipedia.org/wiki/Python
글자 Azərbaycanca
https://az.wikipedia.org/wiki/Python_(proqramla%C5%9Fd%C4%B1rma_dili)
글자 تۆرکجه
https://azb.wikipedia.org/wiki/%D9%BE%D8%A7%DB%8C%D8%AA%D9%88%D9%86
글자 Basa Bali
https://ban.wikipedia.org/wiki/Python
글자 Беларуская (тарашкевіца)
https://be-tarask.wikipedia.org/wiki/Python
글자 Беларуская
https://be.wikipedia.org/wiki/Python_(%D0%BC%D0%BE%D0%B2%D0%B0_%D0%BF%D1%80%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%B0%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F)
글자 Български
https://bg.wikipedia.org/wiki/Python
글자 भोजपुरी
https://bh.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%87%E0%A4%A5%E0%A4%A8
글자 বাংলা
https://bn.wikipedia.org/wiki/%E0%A6%AA%E0%A6%BE%E0%A6%87%E0%A6%A5%E0%A6%A8_(%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A7%8B%E0%A6%97%E0%A7%8D%E0%A6%B0%E0%A6%BE%E0%A6%AE%E0%A6%BF%E0%A6%82_%E0%A6%AD%E0%A6%BE%E0%A6%B7%E0%A6%BE)
글자 Brezhoneg
https://br.wikipedia.org/wiki/Python_(lavar_programmi%C3%B1)
글자 Bosanski
https://bs.wikipedia.org/wiki/Python_(programski_jezik)
글자 Basa Ugi
https://bug.wikipedia.org/wiki/Python
글자 Català
https://ca.wikipedia.org/wiki/Python
글자 Cebuano
https://ceb.wikipedia.org/wiki/Python_(programming_language)
글자 کوردی
https://ckb.wikipedia.org/wiki/%D9%BE%D8%A7%DB%8C%D8%AA%DB%86%D9%86_(%D8%B2%D9%85%D8%A7%D9%86%DB%8C_%D8%A8%DB%95%D8%B1%D9%86%D8%A7%D9%85%DB%95%D8%B3%D8%A7%D8%B2%DB%8C)
글자 Čeština
https://cs.wikipedia.org/wiki/Python
글자 Cymraeg
https://cy.wikipedia.org/wiki/Python_(iaith_raglennu)
글자 Dansk
https://da.wikipedia.org/wiki/Python_(programmeringssprog)
글자 Deutsch
https://de.wikipedia.org/wiki/Python_(Programmiersprache)
글자 Kadazandusun
https://dtp.wikipedia.org/wiki/Python_(boros_tokud)
글자 Ελληνικά
https://el.wikipedia.org/wiki/Python
글자 English
https://en.wikipedia.org/wiki/Python_(programming_language)
글자 Esperanto
https://eo.wikipedia.org/wiki/Python_(programlingvo)
글자 Español
https://es.wikipedia.org/wiki/Python
글자 Eesti
https://et.wikipedia.org/wiki/Python_(programmeerimiskeel)
글자 Euskara
https://eu.wikipedia.org/wiki/Python_(informatika)
글자 فارسی
https://fa.wikipedia.org/wiki/%D9%BE%D8%A7%DB%8C%D8%AA%D9%88%D9%86_(%D8%B2%D8%A8%D8%A7%D9%86_%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%88%DB%8C%D8%B3%DB%8C)
글자 Suomi
https://fi.wikipedia.org/wiki/Python_(ohjelmointikieli)
글자 Na Vosa Vakaviti
https://fj.wikipedia.org/wiki/Python
글자 Français
https://fr.wikipedia.org/wiki/Python_(langage)
글자 Galego
https://gl.wikipedia.org/wiki/Python
글자 گیلکی
https://glk.wikipedia.org/wiki/%D9%BE%D8%A7%D9%8A%D8%AA%D8%A4%D9%86_(%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%E2%80%8C%D9%86%D9%8A%D9%88%D9%8A%D8%B3%D9%8A_%D8%B2%D9%88%D8%A7%D9%86)
글자 ગુજરાતી
https://gu.wikipedia.org/wiki/%E0%AA%AA%E0%AA%BE%E0%AA%AF%E0%AA%A5%E0%AB%8B%E0%AA%A8_(%E0%AA%AA%E0%AB%8D%E0%AA%B0%E0%AB%8B%E0%AA%97%E0%AB%8D%E0%AA%B0%E0%AA%BE%E0%AA%AE%E0%AA%BF%E0%AA%82%E0%AA%97_%E0%AA%AD%E0%AA%BE%E0%AA%B7%E0%AA%BE)
글자 Hausa
https://ha.wikipedia.org/wiki/Python_programming_language
글자 עברית
https://he.wikipedia.org/wiki/%D7%A4%D7%99%D7%99%D7%AA%D7%95%D7%9F
글자 हिन्दी
https://hi.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%87%E0%A4%A5%E0%A4%A8
글자 Hrvatski
https://hr.wikipedia.org/wiki/Python_(programski_jezik)
글자 Magyar
https://hu.wikipedia.org/wiki/Python_(programoz%C3%A1si_nyelv)
글자 Հայերեն
https://hy.wikipedia.org/wiki/Python
글자 Interlingua
https://ia.wikipedia.org/wiki/Python_(linguage_de_programmation)
글자 Bahasa Indonesia
https://id.wikipedia.org/wiki/Python_(bahasa_pemrograman)
글자 Ido
https://io.wikipedia.org/wiki/Python
글자 Íslenska
https://is.wikipedia.org/wiki/Python_(forritunarm%C3%A1l)
글자 Italiano
https://it.wikipedia.org/wiki/Python
글자 日本語
https://ja.wikipedia.org/wiki/Python
글자 La .lojban.
https://jbo.wikipedia.org/wiki/paiton
글자 ქართული
https://ka.wikipedia.org/wiki/%E1%83%9E%E1%83%90%E1%83%98%E1%83%97%E1%83%9D%E1%83%9C%E1%83%98_(%E1%83%9E%E1%83%A0%E1%83%9D%E1%83%92%E1%83%A0%E1%83%90%E1%83%9B%E1%83%98%E1%83%A0%E1%83%94%E1%83%91%E1%83%98%E1%83%A1_%E1%83%94%E1%83%9C%E1%83%90)
글자 Qaraqalpaqsha
https://kaa.wikipedia.org/wiki/Python_(programmalast%C4%B1r%C4%B1w_tili)
글자 Қазақша
https://kk.wikipedia.org/wiki/Python
글자 ភាសាខ្មែរ
https://km.wikipedia.org/wiki/%E1%9E%95%E1%9E%B6%E1%9E%99%E1%9E%90%E1%9E%BB%E1%9E%93
글자 Kurdî
https://ku.wikipedia.org/wiki/Python_(ziman%C3%AA_bernamesaziy%C3%AA)
글자 Кыргызча
https://ky.wikipedia.org/wiki/Python
글자 Latina
https://la.wikipedia.org/wiki/Python_(lingua_programmationis)
글자 Lombard
https://lmo.wikipedia.org/wiki/Python
글자 ລາວ
https://lo.wikipedia.org/wiki/%E0%BB%84%E0%BA%9E%E0%BA%97%E0%BA%AD%E0%BA%99_(%E0%BA%9E%E0%BA%B2%E0%BA%AA%E0%BA%B2%E0%BB%82%E0%BA%9B%E0%BA%A3%E0%BB%81%E0%BA%81%E0%BA%A3%E0%BA%A1)
글자 Lietuvių
https://lt.wikipedia.org/wiki/Python
글자 Latviešu
https://lv.wikipedia.org/wiki/Python_(programm%C4%93%C5%A1anas_valoda)
글자 Македонски
https://mk.wikipedia.org/wiki/%D0%9F%D0%B0%D1%98%D1%82%D0%BE%D0%BD_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%81%D0%BA%D0%B8_%D1%98%D0%B0%D0%B7%D0%B8%D0%BA)
글자 മലയാളം
https://ml.wikipedia.org/wiki/%E0%B4%AA%E0%B5%88%E0%B4%A4%E0%B5%8D%E0%B4%A4%E0%B5%BA_(%E0%B4%AA%E0%B5%8D%E0%B4%B0%E0%B5%8B%E0%B4%97%E0%B5%8D%E0%B4%B0%E0%B4%BE%E0%B4%AE%E0%B4%BF%E0%B4%99%E0%B5%8D%E0%B4%99%E0%B5%8D_%E0%B4%AD%E0%B4%BE%E0%B4%B7)
글자 Монгол
https://mn.wikipedia.org/wiki/Python
글자 मराठी
https://mr.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%AF%E0%A4%A5%E0%A4%A8_(%E0%A4%86%E0%A4%9C%E0%A5%8D%E0%A4%9E%E0%A4%BE%E0%A4%B5%E0%A4%B2%E0%A5%80_%E0%A4%AD%E0%A4%BE%E0%A4%B7%E0%A4%BE)
글자 Bahasa Melayu
https://ms.wikipedia.org/wiki/Python
글자 မြန်မာဘာသာ
https://my.wikipedia.org/wiki/Python_(programming_language)
글자 Plattdüütsch
https://nds.wikipedia.org/wiki/Python_(Programmeerspraak)
글자 नेपाली
https://ne.wikipedia.org/wiki/%E0%A4%AA%E0%A4%BE%E0%A4%87%E0%A4%A5%E0%A4%A8_(%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A5%8B%E0%A4%97%E0%A4%BE%E0%A4%AE%E0%A4%BF%E0%A4%99_%E0%A4%AD%E0%A4%BE%E0%A4%B7%E0%A4%BE)
글자 Nederlands
https://nl.wikipedia.org/wiki/Python_(programmeertaal)
글자 Norsk nynorsk
https://nn.wikipedia.org/wiki/Python
글자 Norsk bokmål
https://no.wikipedia.org/wiki/Python
글자 ߒߞߏ
https://nqo.wikipedia.org/wiki/%DF%94%DF%8A%DF%8C%DF%95%DF%90%DF%B2%DF%AC
글자 Livvinkarjala
https://olo.wikipedia.org/wiki/Python
글자 ଓଡ଼ିଆ
https://or.wikipedia.org/wiki/%E0%AC%AA%E0%AC%BE%E0%AC%87%E0%AC%A5%E0%AC%A8%E0%AD%8D_(%E0%AC%AA%E0%AD%8D%E0%AC%B0%E0%AD%8B%E0%AC%97%E0%AD%8D%E0%AC%B0%E0%AC%BE%E0%AC%AE%E0%AC%BF%E0%AC%82_%E0%AC%AD%E0%AC%BE%E0%AC%B7%E0%AC%BE)
글자 ਪੰਜਾਬੀ
https://pa.wikipedia.org/wiki/%E0%A8%AA%E0%A8%BE%E0%A8%88%E0%A8%A5%E0%A8%A8_(%E0%A8%AA%E0%A9%8D%E0%A8%B0%E0%A9%8B%E0%A8%97%E0%A8%B0%E0%A8%BE%E0%A8%AE%E0%A8%BF%E0%A9%B0%E0%A8%97_%E0%A8%AD%E0%A8%BE%E0%A8%B8%E0%A8%BC%E0%A8%BE)
글자 Polski
https://pl.wikipedia.org/wiki/Python
글자 Piemontèis
https://pms.wikipedia.org/wiki/Python_(lengagi_%C3%ABd_programassion)
글자 پنجابی
https://pnb.wikipedia.org/wiki/%D9%BE%D8%A7%D8%A6%DB%8C%D8%AA%DA%BE%D9%86_(%DA%A9%D9%85%D9%BE%DB%8C%D9%88%D9%B9%D8%B1_%D8%A8%D9%88%D9%84%DB%8C)
글자 Português
https://pt.wikipedia.org/wiki/Python
글자 Runa Simi
https://qu.wikipedia.org/wiki/Python
글자 Română
https://ro.wikipedia.org/wiki/Python
글자 Русский
https://ru.wikipedia.org/wiki/Python
글자 Саха тыла
https://sah.wikipedia.org/wiki/Python
글자 ᱥᱟᱱᱛᱟᱲᱤ
https://sat.wikipedia.org/wiki/%E1%B1%AF%E1%B1%9F%E1%B1%AD%E1%B1%9B%E1%B1%B7%E1%B1%9A%E1%B1%B1_(%E1%B1%AF%E1%B1%A8%E1%B1%B3%E1%B1%9C%E1%B1%BD%E1%B1%A8%E1%B1%9F%E1%B1%A2%E1%B1%A4%E1%B1%9D_%E1%B1%AF%E1%B1%9F%E1%B1%B9%E1%B1%A8%E1%B1%A5%E1%B1%A4)
글자 Scots
https://sco.wikipedia.org/wiki/Python_(programmin_leid)
글자 Srpskohrvatski / српскохрватски
https://sh.wikipedia.org/wiki/Python_(programski_jezik)
글자 တႆး
https://shn.wikipedia.org/wiki/Python_(programming_language)
글자 සිංහල
https://si.wikipedia.org/wiki/%E0%B6%B4%E0%B6%BA%E0%B7%92%E0%B6%AD%E0%B6%B1%E0%B7%8A
글자 Simple English
https://simple.wikipedia.org/wiki/Python_(programming_language)
글자 Slovenčina
https://sk.wikipedia.org/wiki/Python_(programovac%C3%AD_jazyk)
글자 Slovenščina
https://sl.wikipedia.org/wiki/Python_(programski_jezik)
글자 Shqip
https://sq.wikipedia.org/wiki/Python
글자 Српски / srpski
https://sr.wikipedia.org/wiki/Python_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%81%D0%BA%D0%B8_%D1%98%D0%B5%D0%B7%D0%B8%D0%BA)
글자 Svenska
https://sv.wikipedia.org/wiki/Python_(programspr%C3%A5k)
글자 Kiswahili
https://sw.wikipedia.org/wiki/Python_(lugha_ya_programu)
글자 தமிழ்
https://ta.wikipedia.org/wiki/%E0%AE%AA%E0%AF%88%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AE%BE%E0%AE%A9%E0%AF%8D
글자 తెలుగు
https://te.wikipedia.org/wiki/%E0%B0%AA%E0%B1%88%E0%B0%A5%E0%B0%BE%E0%B0%A8%E0%B1%8D_(%E0%B0%95%E0%B0%82%E0%B0%AA%E0%B1%8D%E0%B0%AF%E0%B1%82%E0%B0%9F%E0%B0%B0%E0%B1%8D_%E0%B0%AD%E0%B0%BE%E0%B0%B7)
글자 Тоҷикӣ
https://tg.wikipedia.org/wiki/Python
글자 ไทย
https://th.wikipedia.org/wiki/%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%9E%E0%B8%97%E0%B8%AD%E0%B8%99
글자 Tagalog
https://tl.wikipedia.org/wiki/Python_(wikang_pamprograma)
글자 Toki pona
https://tok.wikipedia.org/wiki/toki_ilo_Pason
글자 Türkçe
https://tr.wikipedia.org/wiki/Python
글자 Татарча / tatarça
https://tt.wikipedia.org/wiki/Python
글자 ئۇيغۇرچە / Uyghurche
https://ug.wikipedia.org/wiki/%D9%BE%D8%A7%D9%8A%D8%B3%D9%88%D9%86
글자 Українська
https://uk.wikipedia.org/wiki/Python
글자 اردو
https://ur.wikipedia.org/wiki/%D9%BE%D8%A7%D8%A6%DB%8C%D8%AA%DA%BE%D9%86_(%D9%BE%D8%B1%D9%88%DA%AF%D8%B1%D8%A7%D9%85%D9%86%DA%AF_%D8%B2%D8%A8%D8%A7%D9%86)
글자 Oʻzbekcha / ўзбекча
https://uz.wikipedia.org/wiki/Python
글자 Tiếng Việt
https://vi.wikipedia.org/wiki/Python_(ng%C3%B4n_ng%E1%BB%AF_l%E1%BA%ADp_tr%C3%ACnh)
글자 Walon
https://wa.wikipedia.org/wiki/Python_(lingaedje_%C3%A9ndjolike)
글자 Winaray
https://war.wikipedia.org/wiki/Python_(programming_language)
글자 吴语
https://wuu.wikipedia.org/wiki/Python
글자 მარგალური
https://xmf.wikipedia.org/wiki/Python_(%E1%83%9E%E1%83%A0%E1%83%9D%E1%83%92%E1%83%A0%E1%83%90%E1%83%9B%E1%83%98%E1%83%A0%E1%83%90%E1%83%A4%E1%83%90%E1%83%A8_%E1%83%9C%E1%83%98%E1%83%9C%E1%83%90)
글자 文言
https://zh-classical.wikipedia.org/wiki/%E8%9F%92%E8%AA%9E
글자 閩南語 / Bân-lâm-gí
https://zh-min-nan.wikipedia.org/wiki/Python
글자 粵語
https://zh-yue.wikipedia.org/wiki/Python
글자 中文
https://zh.wikipedia.org/wiki/Python
글자 링크 편집
https://www.wikidata.org/wiki/Special:EntityPage/Q28865#sitelinks-wikipedia
글자 문서
/wiki/%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 토론
/wiki/%ED%86%A0%EB%A1%A0:%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 읽기
/wiki/%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 편집
/w/index.php?title=%ED%8C%8C%EC%9D%B4%EC%8D%AC&action=edit
글자 역사 보기
/w/index.php?title=%ED%8C%8C%EC%9D%B4%EC%8D%AC&action=history
글자 읽기
/wiki/%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 편집
/w/index.php?title=%ED%8C%8C%EC%9D%B4%EC%8D%AC&action=edit
글자 역사 보기
/w/index.php?title=%ED%8C%8C%EC%9D%B4%EC%8D%AC&action=history
글자 여기를 가리키는 문서
/wiki/%ED%8A%B9%EC%88%98:%EA%B0%80%EB%A6%AC%ED%82%A4%EB%8A%94%EB%AC%B8%EC%84%9C/%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 가리키는 글의 최근 바뀜
/wiki/%ED%8A%B9%EC%88%98:%EB%A7%81%ED%81%AC%EC%B5%9C%EA%B7%BC%EB%B0%94%EB%80%9C/%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 파일 올리기
//ko.wikipedia.org/wiki/위키백과:파일_올리기
글자 고유 링크
/w/index.php?title=%ED%8C%8C%EC%9D%B4%EC%8D%AC&oldid=41991005
글자 문서 정보
/w/index.php?title=%ED%8C%8C%EC%9D%B4%EC%8D%AC&action=info
글자 이 문서 인용하기
/w/index.php?title=%ED%8A%B9%EC%88%98:%EC%9D%B4%EB%AC%B8%EC%84%9C%EC%9D%B8%EC%9A%A9&page=%ED%8C%8C%EC%9D%B4%EC%8D%AC&id=41991005&wpFormIdentifier=titleform
글자 축약된 URL 얻기
/w/index.php?title=%ED%8A%B9%EC%88%98:UrlShortener&url=https%3A%2F%2Fko.wikipedia.org%2Fwiki%2F%25ED%258C%258C%25EC%259D%25B4%25EC%258D%25AC
글자 기존 파서로 전환
/w/index.php?title=%ED%8C%8C%EC%9D%B4%EC%8D%AC&useparsoid=0
글자 책 만들기
/w/index.php?title=%ED%8A%B9%EC%88%98:%EC%B1%85&bookcmd=book_creator&referer=%ED%8C%8C%EC%9D%B4%EC%8D%AC
글자 PDF로 다운로드
/w/index.php?title=%ED%8A%B9%EC%88%98:DownloadAsPdf&page=%ED%8C%8C%EC%9D%B4%EC%8D%AC&action=show-download-screen
글자 인쇄용 판
/w/index.php?title=%ED%8C%8C%EC%9D%B4%EC%8D%AC&printable=yes
글자 추상 위키백과
https://abstract.wikipedia.org/wiki/Q28865
글자 위키미디어 공용
https://commons.wikimedia.org/wiki/Python_(programming_language)
글자 미디어위키
https://www.mediawiki.org/wiki/Python
글자 위키함수
https://www.wikifunctions.org/wiki/Z610
글자 위키데이터 항목
https://www.wikidata.org/wiki/Special:EntityPage/Q28865
글자
//ko.wikipedia.org/wiki/위키백과:동음이의어_문서
글자 피톤
//ko.wikipedia.org/wiki/피톤
글자 파이썬 (미사일)
//ko.wikipedia.org/wiki/파이썬_(미사일)
글자
//ko.wikipedia.org/wiki/파일:Python_logo_and_wordmark.svg
글자 패러다임
//ko.wikipedia.org/wiki/프로그래밍_패러다임
글자 프로그래밍 패러다임
//ko.wikipedia.org/wiki/프로그래밍_패러다임
글자 객체 지향 프로그래밍
//ko.wikipedia.org/wiki/객체_지향_프로그래밍
글자 명령형 프로그래밍
//ko.wikipedia.org/wiki/명령형_프로그래밍
글자 함수형 프로그래밍
//ko.wikipedia.org/wiki/함수형_프로그래밍
글자 절차적 프로그래밍
//ko.wikipedia.org/wiki/절차적_프로그래밍
글자 반영
//ko.wikipedia.org/wiki/반영_(컴퓨터_과학)
글자 설계자
//ko.wikipedia.org/wiki/소프트웨어_설계
글자 귀도 반 로섬
//ko.wikipedia.org/wiki/귀도_반_로섬
글자 개발자
//ko.wikipedia.org/wiki/프로그래머
글자 파이썬 소프트웨어 재단
//ko.wikipedia.org/wiki/파이썬_소프트웨어_재단
글자 [1]
#cite_note-wikidata-a0eeb389e03a9833ed4781ad19ac2726a42a4ba1-v20-1
글자
https://www.wikidata.org/wiki/Q28865?uselang=ko#P348
글자 라이선스
//ko.wikipedia.org/wiki/소프트웨어_사용권
글자 파이썬 소프트웨어 재단 라이선스
//ko.wikipedia.org/wiki/파이썬_소프트웨어_재단_라이선스
글자 파일 확장자
//ko.wikipedia.org/wiki/파일_확장자
글자 www.python.org
https://www.python.org/
글자 구현체
//ko.wikipedia.org/wiki/프로그래밍_언어_구현체
글자 C파이썬
//ko.wikipedia.org/wiki/C파이썬
글자 IronPython
//ko.wikipedia.org/wiki/IronPython
글자 자이썬
//ko.wikipedia.org/wiki/자이썬
글자 마이크로파이썬
//ko.wikipedia.org/wiki/마이크로파이썬
글자 넘바
//ko.wikipedia.org/wiki/Numba
글자 PyPy
//ko.wikipedia.org/wiki/PyPy
글자 스택리스 파이썬
//ko.wikipedia.org/wiki/스택리스_파이썬
글자 사이썬
//ko.wikipedia.org/wiki/사이썬
글자 R파이썬
//ko.wikipedia.org/wiki/PyPy
글자 ABC
//ko.wikipedia.org/wiki/ABC_(프로그래밍_언어)
글자 알골 68
//ko.wikipedia.org/wiki/알골_(프로그래밍_언어)
글자 C
//ko.wikipedia.org/wiki/C_(프로그래밍_언어)
글자 C++
//ko.wikipedia.org/wiki/C++
글자 딜란
https://en.wikipedia.org/wiki/Dylan%20(programming%20language)
글자 하스켈
//ko.wikipedia.org/wiki/하스켈
글자 아이콘
//ko.wikipedia.org/wiki/아이콘_(프로그래밍_언어)
글자 자바
//ko.wikipedia.org/wiki/자바_(프로그래밍_언어)
글자 리스프
//ko.wikipedia.org/wiki/리스프
글자 모듈라-3
//ko.wikipedia.org/wiki/모듈라-3
글자 펄
//ko.wikipedia.org/wiki/펄
글자 부
https://en.wikipedia.org/wiki/Boo%20(programming%20language)
글자 코브라
https://en.wikipedia.org/wiki/Cobra%20(programming%20language)
글자 커피스크립트
//ko.wikipedia.org/wiki/커피스크립트
글자 D
//ko.wikipedia.org/wiki/D_(프로그래밍_언어)
글자 F#
//ko.wikipedia.org/wiki/F_샤프
글자 팰컨
//ko.wikipedia.org/wiki/팰컨_(프로그래밍_언어)
글자 제니
https://en.wikipedia.org/wiki/Genie%20(programming%20language)
글자 Go
//ko.wikipedia.org/wiki/Go_(프로그래밍_언어)
글자 그루비
//ko.wikipedia.org/wiki/그루비_(프로그래밍_언어)
글자 자바스크립트
//ko.wikipedia.org/wiki/자바스크립트
글자 줄리아
//ko.wikipedia.org/wiki/줄리아_(프로그래밍_언어)
글자 님
https://en.wikipedia.org/wiki/Nim%20(programming%20language)
글자 루비
//ko.wikipedia.org/wiki/루비_(프로그래밍_언어)
글자 스위프트
//ko.wikipedia.org/wiki/스위프트_(프로그래밍_언어)
글자 [2]
#cite_note-2
글자 영어
//ko.wikipedia.org/wiki/영어
글자 [3]
#cite_note-파이썬_역사-3
글자 소프트웨어 엔지니어
//ko.wikipedia.org/wiki/소프트웨어_엔지니어
글자 귀도 반 로섬
//ko.wikipedia.org/wiki/귀도_반_로섬
글자 [4]
#cite_note-4
글자 프로그래밍 언어
//ko.wikipedia.org/wiki/프로그래밍_언어
글자 인터프리터
//ko.wikipedia.org/wiki/인터프리터
글자 객체지향
//ko.wikipedia.org/wiki/객체지향
글자 플랫폼
//ko.wikipedia.org/wiki/플랫폼
글자 동적 타이핑
//ko.wikipedia.org/wiki/동적_타이핑
글자 고대신화에 나오는 커다란 뱀
//ko.wikipedia.org/wiki/피톤
글자 프로그래밍 언어
//ko.wikipedia.org/wiki/프로그래밍_언어
글자 데이터 분석
//ko.wikipedia.org/wiki/데이터_분석
글자 웹 개발
//ko.wikipedia.org/wiki/웹_개발
글자 인공지능
//ko.wikipedia.org/wiki/인공지능
글자 파이썬 소프트웨어 재단
//ko.wikipedia.org/wiki/파이썬_소프트웨어_재단
글자 프로그래밍 언어
//ko.wikipedia.org/wiki/프로그래밍_언어
글자 데이터 분석
//ko.wikipedia.org/wiki/데이터_분석
글자 웹 개발
//ko.wikipedia.org/wiki/웹_개발
글자 인공지능
//ko.wikipedia.org/wiki/인공지능
글자 [5]
#cite_note-5
글자 [6]
#cite_note-6
글자 [7]
#cite_note-7
글자 다중 패러다임 프로그래밍 언어
//ko.wikipedia.org/wiki/다중_패러다임_프로그래밍_언어
글자 객체 지향 프로그래밍
//ko.wikipedia.org/wiki/객체_지향_프로그래밍
글자 구조적 프로그래밍
//ko.wikipedia.org/wiki/구조적_프로그래밍
글자 함수형 프로그래밍
//ko.wikipedia.org/wiki/함수형_프로그래밍
글자 관점 지향 프로그래밍
//ko.wikipedia.org/wiki/관점_지향_프로그래밍
글자 메타프로그래밍
//ko.wikipedia.org/wiki/메타프로그래밍
글자 [8]
#cite_note-AutoNT-13-8
글자 메타객체
//ko.wikipedia.org/wiki/메타객체?action=edit&redlink=1
글자 [9]
#cite_note-AutoNT-14-9
글자 계약에 의한 설계
//ko.wikipedia.org/wiki/계약에_의한_설계
글자 [10]
#cite_note-AutoNT-15-10
글자 [11]
#cite_note-AutoNT-16-11
글자 논리 프로그래밍
//ko.wikipedia.org/wiki/논리_프로그래밍
글자 [12]
#cite_note-AutoNT-17-12
글자 [13]
#cite_note-13
글자 동적 타이핑
//ko.wikipedia.org/wiki/동적_타이핑
글자 메모리 관리
//ko.wikipedia.org/wiki/메모리_관리
글자 참조 횟수 계산
//ko.wikipedia.org/wiki/참조_횟수_계산?action=edit&redlink=1
글자 쓰레기 수집기
//ko.wikipedia.org/wiki/쓰레기_수집_(컴퓨터_과학)
글자 들여쓰기
//ko.wikipedia.org/wiki/들여쓰기
글자 블록
//ko.wikipedia.org/wiki/블록_(프로그래밍)
글자 [14]
#cite_note-AutoNT-53-14
글자 [15]
#cite_note-guttag-15
글자 오프사이드 규칙
//ko.wikipedia.org/wiki/오프사이드_규칙?action=edit&redlink=1
글자 [16]
#cite_note-pep8-16
글자 덕 타이핑
//ko.wikipedia.org/wiki/덕_타이핑
글자 동적 타입
//ko.wikipedia.org/wiki/동적_타입?action=edit&redlink=1
글자 강타입
//ko.wikipedia.org/wiki/강타입?action=edit&redlink=1
글자 모듈로 연산
//ko.wikipedia.org/wiki/모듈로_연산?action=edit&redlink=1
글자 [17]
#cite_note-venners-interview-pt-1-17
글자 네덜란드
//ko.wikipedia.org/wiki/네덜란드
글자 Centrum Wiskunde & Informatica
//ko.wikipedia.org/wiki/Centrum_Wiskunde_&_Informatica?action=edit&redlink=1
글자 귀도 반 로섬
//ko.wikipedia.org/wiki/귀도_반_로섬
글자 [18]
#cite_note-timeline-of-python-18
글자 SETL
//ko.wikipedia.org/wiki/SETL?action=edit&redlink=1
글자 ABC
//ko.wikipedia.org/wiki/ABC_(프로그래밍_언어)
글자 예외 처리
//ko.wikipedia.org/wiki/예외_처리
글자 아메바 운영 체제
//ko.wikipedia.org/wiki/아메바_운영_체제?action=edit&redlink=1
글자 [19]
#cite_note-faq-created-19
글자 [18]
#cite_note-timeline-of-python-18
글자 [18]
#cite_note-timeline-of-python-18
글자 편집

In [61]:
# 링크 보를 데이터프레임으로 저장
link_data = []

for link in links:
    # 링크 걸린 글자만 공백 제거한 후 텍스트에 저장
    text = link.text.strip()

    # href 속성에 들어있는 링크 주소만 href의 변수에 저장
    href = link.get("href")
    
    # 결측 값이 없는 경우에만 데이터 프레임에 저장한다.
    if text != "" and href is not None:
        link_data.append([text, href])

# 리스트를 데이터 프레임으로 변환
pandas_dataframe = pd.DataFrame(link_data, columns=['글자', '링크'])

In [62]:
pandas_dataframe

          글자                                                 링크
0    본문으로 이동                                       #bodyContent
1         대문  /wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%EB...
2      최근 바뀜  /wiki/%ED%8A%B9%EC%88%98:%EC%B5%9C%EA%B7%BC%EB...
3      요즘 화제  /wiki/%ED%8F%AC%ED%84%B8:%EC%9A%94%EC%A6%98_%E...
4     임의 문서로  /wiki/%ED%8A%B9%EC%88%98:%EC%9E%84%EC%9D%98%EB...
..       ...                                                ...
804      개발자                    https://developer.wikimedia.org
805       통계     https://stats.wikimedia.org/#/ko.wikipedia.org
806    쿠키 정책  https://foundation.wikimedia.org/wiki/Special:...
807   모바일 보기  //ko.wikipedia.org/w/index.php?title=%ED%8C%8C...
808     새 주제                                                  #

[809 rows x 2 columns]

In [68]:
# 라이브러리 불러오기
import requests
import pandas as pd
from dotenv import load_dotenv
import os

load_dotenv()

KAKAO_MAP_KEY = os.getenv('KAKAO_MAP_KEY')

In [76]:
def get_geocoding(place):
    url = 'https://dapi.kakao.com/v2/local/search/address.json'

    headers = {
        'Authorization': f"KakaoAK {KAKAO_MAP_KEY}"
    }

    # place 는 함수에 전달받은 주소를 저장하는 변수
    # 카카오 API의 query 값으로 전달되어 해당 주소의 위도와 경도를 검색
    params = {
        'query': place
    }

    response = requests.get(url, headers=headers, params=params)
    result = response.json()
    return result['documents'][0]['y'], result['documents'][0]['x']

In [79]:
lat = [] # 위도
lng = [] # 경도

# 장소(주소) 리스트
places = ['서울특별시 종로구 세종대로 175',
          '서울특별시 서초구 서초동 700',
          '부산광역시 해운대구 해운대해변로 264']

i = 0
for place in places:
    i += 1
    try:
        print(i, place)
        place_lat, place_lng = get_geocoding(place)
        lat.append(place_lat) # 위도를 리스트에 추가
        lng.append(place_lng) # 경도를 리스트에 추가
    except Exception as e:
        print('오류 발생', e)
        lat.append('')
        lng.append('')

df = pd.DataFrame({'위도': lat, '경도': lng}, index=places)
df

1 서울특별시 종로구 세종대로 175
2 서울특별시 서초구 서초동 700
3 부산광역시 해운대구 해운대해변로 264

                                     위도                경도
서울특별시 종로구 세종대로 175     37.5718478584908  126.976168275947
서울특별시 서초구 서초동 700      37.4810862955299  127.015245160054
부산광역시 해운대구 해운대해변로 264  35.1591069824231  129.160283786856